#!/bin/bash

# test if the script is started by root user. If not, exit
  if [ "0$UID" -ne 0 ]; then
     echo "Only root can run $(basename $0)"; exit 1
  fi

wait
echo ""
echo "***************************************************************************"
echo "Building Colorado-Linux..."
echo "***************************************************************************"
echo ""

# Install modules

for module in $(ls modules)
do
	echo ""
	echo "***************************************************************************"
	echo "Installing Module: $module"
	echo "***************************************************************************"
	cd ./modules/$module
	. ./build
	cd ../..
	echo ""
	echo "***************************************************************************"
	echo "$module is complete"
	echo "***************************************************************************"
	echo ""

done

wait
echo ""
echo "***************************************************************************"
echo "Cleaning up after install..."
echo "***************************************************************************"
echo ""

. ./cleanup

wait
echo ""
echo "***************************************************************************"
echo "Finished configuring Colorado-Linux"
echo "***************************************************************************"
echo ""
echo ""

